version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: splitwise_db
    restart: always
    environment:
      POSTGRES_USER: splitwise_user
      POSTGRES_PASSWORD: splitwise_password
      POSTGRES_DB: splitwise_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: